services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3124:3124
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    env_file:
      - .env
    volumes:
      - mysql_storage:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mysql_storage:
